#!/usr/bin/env bash
set -eo pipefail; [[ -n "$PLUSHU_TRACE" ]] && set -x

remote=$1
target=$2

git clone $remote "$PLUSHU_PLUGINS_DIR/$target"

# When installing as root, give the plushu user ownership of everything
# within the newly-cloned plugin
if [[ "$EUID" == 0 ]]; then
  chown -R "$PLUSHU_USER:" "$PLUSHU_PLUGINS_DIR/$target"
fi

# If the newly-cloned plugin has an install script
if [[ -f "$PLUSHU_PLUGINS_DIR/$target/install" ]]; then

  # We don't test for executable status, we just
  # let the shell fail if the install script isn't set executable
  PLUSHU_PLUGIN_NAME="$target" \
  PLUSHU_PLUGIN_PATH="$PLUSHU_PLUGINS_DIR/$target" \
    "$PLUSHU_PLUGINS_DIR/$target/install"

else
  # Notify that the plugin has been installed
  # in lieu of a more complex
  echo "Plugin '$target' installed."
fi
