#!/usr/bin/env bash
set -eo pipefail; [[ -n "$PLUSHU_TRACE" ]] && set -x

disabled_plugins_dir=$PLUSHU_DIR/disabled-plugins

# If no plugin name was specified
if [[ -z "$2" ]]; then
  echo "Missing name of plugin to disable" >&2
  exit 1
fi

# For each plugin specified
while [[ -n "$2" ]]; do
  # If that plugin exists
  if [[ -d "$PLUSHU_PLUGINS_DIR/$2" ]]; then

    mkdir -p "$disabled_plugins_dir"

    # disable the plugin
    mv "$PLUSHU_PLUGINS_DIR/$2" "$disabled_plugins_dir/$2"
    echo "Plugin '$2' disabled."

  # If that plugin does not exist
  else
    echo "Plugin not found: $2" >&2
    exit 1
  fi
  shift
done
