#!/usr/bin/env bash
set -eo pipefail; [[ -n "$PLUSHU_TRACE" ]] && set -x

# If a plugin name was specified
if [[ -n $2 ]]; then

  case "$2" in
    git:*|ssh:*|*@*:*|http:*|https:*)
      remote=$2
      defname=${2#*:}
      defname=${defname##*/}
      ;;
    */*)
      remote=https://github.com/$2.git
      defname=${2##*/}
      ;;
    *)
      remote=https://github.com/plushu/plushu-${2#plushu-}.git
      defname=$2
      ;;
  esac
  defname=${defname#plushu-}
  defname=${defname%-plugin}
  defname=${defname%.git}
  target=${3:-$defname}
  target_dir="$PLUSHU_PLUGINS_DIR/$target"

  # If the plugin already exists
  if [[ -e "$target_dir" ]]; then
    cat >&2 <<EOF
Plugin '$target' is already installed.
Use \`plushu $PLUSHU_PLUGIN_NAME:reinstall $target\` to rerun its install script,
or \`plushu $PLUSHU_PLUGIN_NAME:uninstall $target\` first if you want to do a hard reinstall.
EOF
    exit 1

  # If the plugin isn't already installed, install it
  else
    "$PLUSHU_ROOT/lib/plushook" install-plugin "$remote" "$target"
  fi

# If no plugin name was specified
else
  echo "Missing name of plugin to install" >&2
  exit 1
fi
