#!/usr/bin/env bash
set -eo pipefail; [[ -n "$PLUSHU_TRACE" ]] && set -x

# If a plugin name was specified
if [[ -n $2 ]]; then

  case "$2" in
    git:*|ssh:*|*@*:*|http:*|https:*)
      remote=$2
      defname=${2#*:}
      defname=${defname##*/}
      ;;
    */*)
      remote=https://github.com/$2.git
      defname=${2##*/}
      ;;
    *)
      remote=https://github.com/plushu/plushu-${2#plushu-}.git
      defname=$2
      ;;
  esac
  defname=${defname#plushu-}
  defname=${defname%-plugin}
  defname=${defname%.git}
  plugin=${3:-$defname}
  plugin_dir="$PLUSHU_PLUGINS_DIR/$plugin"

  # If the plugin already exists
  if [[ -e "$plugin_dir" ]]; then
    cat >&2 <<EOF
Plugin '$plugin' is already installed.
Use \`plushu $PLUSHU_PLUGIN_NAME:reinstall $plugin\` to rerun its install script,
or \`plushu $PLUSHU_PLUGIN_NAME:uninstall $plugin\` first if you want to do a hard reinstall.
EOF
    exit 1

  # If the plugin isn't already installed, install it
  else
    "$PLUSHU_ROOT/lib/plushook" install-plugin "$plugin" "$remote"
  fi

# If no plugin name was specified
else
  echo "Missing name of plugin to install" >&2
  exit 1
fi
