#!/usr/bin/env bash
set -eo pipefail; [[ -n "$PLUSHU_TRACE" ]] && set -x

# If no plugin name was specified
if [[ -z "$2" ]]; then
  echo "Missing name of plugin to uninstall" >&2
  exit 1
fi

# For each plugin specified
while [[ -n "$2" ]]; do
  # If that plugin exists
  if [[ -d "$PLUSHU_PLUGINS_DIR/$2" ]]; then

    # If that plugin has an uninstall script
    if [[ -f "$PLUSHU_PLUGINS_DIR/$2/uninstall" ]]; then

      # We don't test for executable status, we just
      # let the shell fail if the uninstall script isn't set executable
      PLUSHU_PLUGIN_NAME="$2" PLUSHU_PLUGIN_PATH="$PLUSHU_PLUGINS_DIR/$2" \
        "$PLUSHU_PLUGINS_DIR/$2/uninstall"
    fi

    # Remove the plugin
    rm -rf "$PLUSHU_PLUGINS_DIR/$2"
    echo "Plugin '$2' uninstalled."

  # If that plugin does not exist
  else
    echo "Plugin not found: $2" >&2
    exit 1
  fi
  shift
# If no plugin name was specified
done
