#!/usr/bin/env bash
set -eo pipefail; [[ -n "$PLUSHU_TRACE" ]] && set -x

# If at least one plugin name was specified
if [[ -n "$2" ]]; then
  plugins=()
  # For each plugin specified
  while [[ -n "$2" ]]; do
    # If that plugin exists
    if [[ -d "$PLUSHU_PLUGINS_DIR/$2" ]]; then
      # Add it to the update list
      plugins+=("$PLUSHU_PLUGINS_DIR/$2")

    # If that plugin does not exist
    else
      echo "Plugin not found: $2" >&2
      exit 1
    fi
    shift
  done
# If no plugin name was specified
else
  # Update ALL the plugins
  plugins=("$PLUSHU_PLUGINS_DIR"/*)
fi

# Update each plugin to update
for plugin in "${plugins[@]}"; do
  "$PLUSHU_ROOT/lib/plushook" update-plugin "${plugin##*/}"
done
