#!/usr/bin/env bash
set -eo pipefail; [[ -n "$PLUSHU_TRACE" ]] && set -x

plugin=$1
plugin_dir="$PLUSHU_PLUGINS_DIR/$plugin"

# If the plugin exists
if [[ -d "$plugin_dir" ]]; then
  # Retrieve it
  "$PLUSHU_ROOT/lib/plushook" update-dir "$plugin_dir" "$plugin" 3>&1 |
  while read -a update; do
    # If the plugin was updated
    if [[ -n "${update[1]}" ]]; then
      # If this plugin has an update script
      if [[ -f ./update ]]; then

        # We don't test for executable status, we just
        # let the shell fail if the update script isn't set executable
        PLUSHU_PLUGIN_NAME=$plugin PLUSHU_PLUGIN_PATH=$plugin_dir \
          ./update "${update[@]}"
      fi
    # Otherwise, mention the system declaring it to be up to date
    else
      echo "${update[0]}: $plugin is up to date"
    fi
  done
fi
